language: python

addons:
  postgresql: "9.4"

python:
  - "2.7"
  - "3.4"

env:
  - DJANGO="django==1.8.2"

install:
  - pip install $DJANGO
  - pip install psycopg2
  - export PYTHONPATH=.

script:
  - python reports/runtests/runtests.py

before_script:
  - psql -c 'CREATE EXTENSION postgis;' -d travis -U postgres
