language: python

addons:
  postgresql: "13.1"

python:
  - "3.8"

env:
  - DJANGO="django>=3.0,<4.0"
  - DJANGO="django>=2.0,<3.0"

install:
  - pip install $DJANGO
  - pip install psycopg2
  - export PYTHONPATH=.

script:
  - python reports/runtests/runtests.py

before_script:
  - psql -c 'CREATE EXTENSION postgis;' -d travis -U postgres
