version: 0.2

env:
  shell: bash
phases:
  install:
    runtime-versions:
      python: 3.11
  pre_build:
    commands:
      - export CODEARTIFACT_AUTH_TOKEN=$(aws codeartifact get-authorization-token --domain criticalstart --domain-owner 818476207984 --query authorizationToken --duration-seconds 1800 --output text)
      - export PIP_INDEX_URL="https://aws:${CODEARTIFACT_AUTH_TOKEN}@criticalstart-818476207984.d.codeartifact.us-west-2.amazonaws.com/pypi/criticalstart_global/simple/"
      - pip install black==23.1.0
      - pip install -r requirements-build.txt
      - REPOSITORY_BASE=818476207984.dkr.ecr.us-west-2.amazonaws.com
      - AWS_DEFAULT_REGION=us-west-2
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $REPOSITORY_BASE

      - REPOSITORY_BASE=818476207984.dkr.ecr.us-west-2.amazonaws.com
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $REPOSITORY_BASE
      - echo Logging in to Amazon CodeArtifact...
      - export CODEARTIFACT_AUTH_TOKEN=$(aws codeartifact get-authorization-token --domain criticalstart --domain-owner 818476207984 --query authorizationToken --duration-seconds 1800 --output text)
      - export PIP_INDEX_URL="https://aws:${CODEARTIFACT_AUTH_TOKEN}@criticalstart-818476207984.d.codeartifact.us-west-2.amazonaws.com/pypi/criticalstart_global/simple/"

      # Build dependencies
      - pip install -r requirements-build.txt

      # Build environment
      - export COMPOSE_FILE=docker-compose.codebuild.yml
      - docker-compose up -d postgres
      - docker-compose build --build-arg PIP_INDEX_URL app
  build:
    commands:
      - black --check .
      - docker-compose run app tox
      - python -m build
  post_build:
    commands:
      - |
        if [ "$CODEBUILD_WEBHOOK_TRIGGER" == "branch/master" ] && [ "$CODEBUILD_BUILD_SUCCEEDING" -eq "1" ]; then
          aws codeartifact login --tool twine --domain criticalstart --domain-owner 818476207984 --repository criticalstart_global
          twine upload --repository codeartifact dist/*
        else
          echo Cannot upload to CodeArtifact
        fi

cache:
  paths:
    - "/root/.cache/pip/**/*/"
