version: "2"
services:

  postgres:
    image: postgres:13.1-alpine
    ports:
      - 5432:5432
    volumes:
      - ./tmp/postgres:/var/lib/postgresql/13.1
    environment:
        POSTGRES_USER: docker
        POSTGRES_PASSWORD: docker
    networks:
      - reports

networks:
  reports:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.144.0/24
          gateway: 172.16.144.1
