# Generated by Django 2.2.19 on 2021-03-25 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0005_auto_20201211_1416'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='origin_report_id',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='status',
            field=models.CharField(
                choices=[
                    ('running', 'Running'), ('completed', 'Completed'),
                    ('failed', 'Failed'), ('skipped', 'Skipped')
                ],
                default='running',
                max_length=256
            ),
        ),
    ]
