# Generated by Django 3.2.12 on 2022-03-11 05:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reports", "0006_auto_20210325_2053"),
    ]

    operations = [
        migrations.AlterField(
            model_name="report",
            name="config",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name="reportschedule",
            name="config",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name="reportschedule",
            name="schedule",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
