# Generated by Django 4.2.14 on 2024-09-11 01:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reports", "0007_auto_20220311_0537"),
    ]

    operations = [
        migrations.AddField(
            model_name="report",
            name="report_timezone",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="reportschedule",
            name="report_timezone",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name="report",
            name="report",
            field=models.CharField(
                choices=[
                    ("account_compromise", "Account Compromise Report"),
                    ("assessment_comparison", "Assessment comparison"),
                    ("assessment_recommendations", "Assessment recommendations"),
                    ("auth0_compliance", "Auth0 Compliance Report"),
                    ("auth0_offboarding", "Vendor Access and Cleanup Report"),
                    ("carbonblack_audit", "Carbonblack Host Audit Report"),
                    ("customer_orchestration_audit", "Customer Orchestration Audit"),
                    ("customer_output", "Customer Output Report"),
                    ("cylance_billing", "Cylance Billing Report"),
                    (
                        "cylanceguard_closed_incidents_type",
                        "Cylance Closed Alerts By Trigger Event Type",
                    ),
                    ("dashboards_report", "Executive Dashboard Report"),
                    ("dashboards_presentation", "Executive Dashboard Presentation"),
                    ("data_sources", "SIEM Data Source Health"),
                    ("defender_365_user_count", "Microsoft 365 Defender Users Report"),
                    ("email_phishing", "Email Phishing Report"),
                    ("mssp performance", "Escalated Alerts Detail Report"),
                    ("escalation_to_client", "Escalation To Client Details Report"),
                    ("eula_acceptance", "EULA Acceptance Report"),
                    ("executive", "Executive Report Combined"),
                    ("expiring_event_matchers", "Expiring Event Matchers Report"),
                    ("installed_products", "Installed Products Report"),
                    ("ioc_efficiency", "IOC Efficiency Report"),
                    ("ioc_status", "IOC Status Report"),
                    ("ioc_technologies", "IOC Technologies Report"),
                    (
                        "mdatp_detailed_endpoint_info",
                        "Windows Defender for Endpoint Detailed Report",
                    ),
                    ("mdr-kpi-data", "MDR KPI Data"),
                    (
                        "ms_security_server_usage",
                        "Microsoft Security Server Usage Report",
                    ),
                    (
                        "azure_sentinel_correlation",
                        "Microsoft Sentinel Correlation Report",
                    ),
                    (
                        "microsoft_sentinel_potential_ootb_content",
                        "Microsoft Sentinel Potential Out of the Box Content",
                    ),
                    ("mitre_mitigations", "MITRE Mitigations"),
                    ("operational_review", "Operational Review Report"),
                    ("orchestration_efficiency", "Orchestration Efficiency Report"),
                    ("organization", "Organization Report"),
                    ("overlapping_playbooks", "Overlapping Playbooks Report"),
                    ("portal_efficiency_report", "Portal Efficiency Report"),
                    ("product_healthcheck", "Product Healthcheck Report"),
                    ("product_license", "Product License Report"),
                    ("product_setup_validation", "Product Setup Report"),
                    ("product_status", "Product Deployment Status Report"),
                    ("siem_coverage", "SIEM Coverage Report"),
                    ("socai_metrics", "SOCAI Metrics Report"),
                    ("tn_change_log", "Threat Navigator Change Log Report"),
                    ("ttr_ttd", "TTR,TTD Report"),
                    ("user_audit", "User Audit"),
                    ("user_authn_audit", "User Authentication Audit Report"),
                    ("user_last_login", "User Last Login Report"),
                    ("user_sign_up", "User Sign-up Report"),
                    (
                        "cbr_endpoints_count",
                        "VMware Carbon Black EDR Endpoints Count Report",
                    ),
                    (
                        "cb_threat_hunter_endpoints_count",
                        "VMware Carbon Black Enterprise EDR Endpoints Count Report",
                    ),
                    (
                        "cbdefense_endpoints_count",
                        "VMware Carbon Black Endpoint Standard Endpoints Count Report",
                    ),
                    (
                        "falcon_endpoints_count",
                        "CrowdStrike Falcon Endpoints Count Report",
                    ),
                    ("cylance_endpoints_count", "Cylance Endpoints Count Report"),
                    (
                        "defender_atp_endpoints_count",
                        "Microsoft Defender for Endpoint Count Report",
                    ),
                    ("deployment_alerts", "Deployment Alerts"),
                    (
                        "sentinel_one_endpoints_count",
                        "SentinelOne Endpoints Count Report",
                    ),
                    (
                        "xdr_endpoints_count",
                        "Palo Alto Cortex XDR or XSIAM for Endpoint Endpoints Count Report",
                    ),
                    (
                        "azure_sentinel_volume_count",
                        "Microsoft Sentinel Ingest Volume Report",
                    ),
                    ("devo_volume_count", "Devo Ingest Volume Report"),
                    (
                        "sentinel_one_endpoints_breakdown",
                        "SentinelOne Endpoints Breakdown Report",
                    ),
                    (
                        "azure_sentinel_alert_tracking",
                        "Microsoft Sentinel Alert Tracking Report",
                    ),
                    (
                        "defender_365_alert_tracking",
                        "Microsoft 365 Defender Alert Tracking Report",
                    ),
                    (
                        "defender_atp_alert_tracking",
                        "Microsoft Defender for Endpoint Alert Tracking Report",
                    ),
                    ("devo_alert_tracking", "Devo Alert Tracking Report"),
                    (
                        "sentinel_one_alert_tracking",
                        "SentinelOne Alert Tracking Report",
                    ),
                    ("splunk_alert_tracking", "Splunk Alert Tracking Report"),
                    (
                        "xdr_alert_tracking",
                        "Palo Alto Cortex XDR or XSIAM for Endpoint Alert Tracking Report",
                    ),
                    ("asset_visibility_statistics", "Asset Visibility Statistics"),
                    (
                        "asset_inventory_critical_systems",
                        "Asset Inventory Critical Systems",
                    ),
                    ("asset_inventory_deleted_hosts", "Asset Inventory Deleted Hosts"),
                    ("asset_inventory_hosts", ""),
                    (
                        "risk_recommendations_risk_recommendations",
                        "Risk Recommendations",
                    ),
                    ("risk_recommendations_audit", "Risk Recommendation Change Audit"),
                    (
                        "azure_sentinel_managed_siem",
                        "Microsoft Sentinel Managed SIEM Report",
                    ),
                    ("vulnerabilities_list", ""),
                    ("data_connectors_activity_logs", "Data Connectors Activity Logs"),
                ],
                max_length=64,
            ),
        ),
        migrations.AlterField(
            model_name="report",
            name="typ",
            field=models.CharField(
                choices=[
                    ("pdf", "PDF Document"),
                    ("docx", "Word Document"),
                    ("xlsx", "Excel Document"),
                    ("csv", "CSV Document"),
                ],
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="reportschedule",
            name="period",
            field=models.CharField(
                choices=[
                    ("daily", "Daily"),
                    ("weekly", "Weekly"),
                    ("monthly", "Monthly"),
                    ("quarterly", "Quarterly"),
                    ("yearly", "Yearly"),
                ],
                default="weekly",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="reportschedule",
            name="report",
            field=models.CharField(
                choices=[
                    ("account_compromise", "Account Compromise Report"),
                    ("assessment_comparison", "Assessment comparison"),
                    ("assessment_recommendations", "Assessment recommendations"),
                    ("auth0_compliance", "Auth0 Compliance Report"),
                    ("auth0_offboarding", "Vendor Access and Cleanup Report"),
                    ("carbonblack_audit", "Carbonblack Host Audit Report"),
                    ("customer_orchestration_audit", "Customer Orchestration Audit"),
                    ("customer_output", "Customer Output Report"),
                    ("cylance_billing", "Cylance Billing Report"),
                    (
                        "cylanceguard_closed_incidents_type",
                        "Cylance Closed Alerts By Trigger Event Type",
                    ),
                    ("dashboards_report", "Executive Dashboard Report"),
                    ("dashboards_presentation", "Executive Dashboard Presentation"),
                    ("data_sources", "SIEM Data Source Health"),
                    ("defender_365_user_count", "Microsoft 365 Defender Users Report"),
                    ("email_phishing", "Email Phishing Report"),
                    ("mssp performance", "Escalated Alerts Detail Report"),
                    ("escalation_to_client", "Escalation To Client Details Report"),
                    ("eula_acceptance", "EULA Acceptance Report"),
                    ("executive", "Executive Report Combined"),
                    ("expiring_event_matchers", "Expiring Event Matchers Report"),
                    ("installed_products", "Installed Products Report"),
                    ("ioc_efficiency", "IOC Efficiency Report"),
                    ("ioc_status", "IOC Status Report"),
                    ("ioc_technologies", "IOC Technologies Report"),
                    (
                        "mdatp_detailed_endpoint_info",
                        "Windows Defender for Endpoint Detailed Report",
                    ),
                    ("mdr-kpi-data", "MDR KPI Data"),
                    (
                        "ms_security_server_usage",
                        "Microsoft Security Server Usage Report",
                    ),
                    (
                        "azure_sentinel_correlation",
                        "Microsoft Sentinel Correlation Report",
                    ),
                    (
                        "microsoft_sentinel_potential_ootb_content",
                        "Microsoft Sentinel Potential Out of the Box Content",
                    ),
                    ("mitre_mitigations", "MITRE Mitigations"),
                    ("operational_review", "Operational Review Report"),
                    ("orchestration_efficiency", "Orchestration Efficiency Report"),
                    ("organization", "Organization Report"),
                    ("overlapping_playbooks", "Overlapping Playbooks Report"),
                    ("portal_efficiency_report", "Portal Efficiency Report"),
                    ("product_healthcheck", "Product Healthcheck Report"),
                    ("product_license", "Product License Report"),
                    ("product_setup_validation", "Product Setup Report"),
                    ("product_status", "Product Deployment Status Report"),
                    ("siem_coverage", "SIEM Coverage Report"),
                    ("socai_metrics", "SOCAI Metrics Report"),
                    ("tn_change_log", "Threat Navigator Change Log Report"),
                    ("ttr_ttd", "TTR,TTD Report"),
                    ("user_audit", "User Audit"),
                    ("user_authn_audit", "User Authentication Audit Report"),
                    ("user_last_login", "User Last Login Report"),
                    ("user_sign_up", "User Sign-up Report"),
                    (
                        "cbr_endpoints_count",
                        "VMware Carbon Black EDR Endpoints Count Report",
                    ),
                    (
                        "cb_threat_hunter_endpoints_count",
                        "VMware Carbon Black Enterprise EDR Endpoints Count Report",
                    ),
                    (
                        "cbdefense_endpoints_count",
                        "VMware Carbon Black Endpoint Standard Endpoints Count Report",
                    ),
                    (
                        "falcon_endpoints_count",
                        "CrowdStrike Falcon Endpoints Count Report",
                    ),
                    ("cylance_endpoints_count", "Cylance Endpoints Count Report"),
                    (
                        "defender_atp_endpoints_count",
                        "Microsoft Defender for Endpoint Count Report",
                    ),
                    ("deployment_alerts", "Deployment Alerts"),
                    (
                        "sentinel_one_endpoints_count",
                        "SentinelOne Endpoints Count Report",
                    ),
                    (
                        "xdr_endpoints_count",
                        "Palo Alto Cortex XDR or XSIAM for Endpoint Endpoints Count Report",
                    ),
                    (
                        "azure_sentinel_volume_count",
                        "Microsoft Sentinel Ingest Volume Report",
                    ),
                    ("devo_volume_count", "Devo Ingest Volume Report"),
                    (
                        "sentinel_one_endpoints_breakdown",
                        "SentinelOne Endpoints Breakdown Report",
                    ),
                    (
                        "azure_sentinel_alert_tracking",
                        "Microsoft Sentinel Alert Tracking Report",
                    ),
                    (
                        "defender_365_alert_tracking",
                        "Microsoft 365 Defender Alert Tracking Report",
                    ),
                    (
                        "defender_atp_alert_tracking",
                        "Microsoft Defender for Endpoint Alert Tracking Report",
                    ),
                    ("devo_alert_tracking", "Devo Alert Tracking Report"),
                    (
                        "sentinel_one_alert_tracking",
                        "SentinelOne Alert Tracking Report",
                    ),
                    ("splunk_alert_tracking", "Splunk Alert Tracking Report"),
                    (
                        "xdr_alert_tracking",
                        "Palo Alto Cortex XDR or XSIAM for Endpoint Alert Tracking Report",
                    ),
                    ("asset_visibility_statistics", "Asset Visibility Statistics"),
                    (
                        "asset_inventory_critical_systems",
                        "Asset Inventory Critical Systems",
                    ),
                    ("asset_inventory_deleted_hosts", "Asset Inventory Deleted Hosts"),
                    ("asset_inventory_hosts", ""),
                    (
                        "risk_recommendations_risk_recommendations",
                        "Risk Recommendations",
                    ),
                    ("risk_recommendations_audit", "Risk Recommendation Change Audit"),
                    (
                        "azure_sentinel_managed_siem",
                        "Microsoft Sentinel Managed SIEM Report",
                    ),
                    ("vulnerabilities_list", ""),
                    ("data_connectors_activity_logs", "Data Connectors Activity Logs"),
                ],
                max_length=64,
            ),
        ),
        migrations.AlterField(
            model_name="reportschedule",
            name="typ",
            field=models.CharField(
                choices=[
                    ("pdf", "PDF Document"),
                    ("docx", "Word Document"),
                    ("xlsx", "Excel Document"),
                    ("csv", "CSV Document"),
                ],
                max_length=32,
            ),
        ),
    ]
