# Generated by Django 4.2.14 on 2024-09-11 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0007_auto_20220311_0537"),
    ]

    operations = [
        migrations.AddField(
            model_name="report",
            name="report_timezone",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="reportschedule",
            name="report_timezone",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
