# Generated by Django 4.2.18 on 2025-06-13 08:48

from django.db import migrations, models
import reports.fields


class Migration(migrations.Migration):
    dependencies = [
        ("reports", "0008_report_report_timezone_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="report",
            name="visibility",
            field=models.CharField(
                choices=[("customer", "Customer facing"), ("internal", "Internal")],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="report",
            name="report",
            field=reports.fields.ChoicesCharField(max_length=64),
        ),
        migrations.AlterField(
            model_name="report",
            name="typ",
            field=reports.fields.ChoicesCharField(max_length=32),
        ),
        migrations.AlterField(
            model_name="reportschedule",
            name="period",
            field=models.CharField(
                choices=[
                    ("daily", "Daily"),
                    ("weekly", "Weekly"),
                    ("monthly", "Monthly"),
                    ("quarterly", "Quarterly"),
                    ("yearly", "Yearly"),
                ],
                default="weekly",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="reportschedule",
            name="report",
            field=reports.fields.ChoicesCharField(max_length=64),
        ),
        migrations.AlterField(
            model_name="reportschedule",
            name="typ",
            field=reports.fields.ChoicesCharField(max_length=32),
        ),
    ]
