# Generated by Django 5.2.3 on 2025-06-16 14:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reports", "0009_report_visibility_alter_report_report_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="reportschedule",
            name="visibility",
            field=models.CharField(
                choices=[("customer", "Customer facing"), ("internal", "Internal")],
                null=True,
            ),
        ),
    ]
